import { Event } from "@/database";
import { connectDB } from "@/lib/mongodb";
import { NextResponse } from "next/server";

// Slugs are generated by the Event model's pre-save hook, so they only ever
// contain lowercase alphanumerics and dashes. Anything else can't match a
// document and is a client mistake, not a 404.
const SLUG_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

// `RouteContext` is generated by `next dev` / `next build` / `next typegen`.
export async function GET(_req: Request, ctx: RouteContext<"/api/events/[slug]">) {
  try {
    const { slug } = await ctx.params;
    const normalized = slug.trim().toLowerCase();

    if (!SLUG_PATTERN.test(normalized)) {
      return NextResponse.json({ message: "Invalid slug" }, { status: 400 });
    }

    await connectDB();

    // `lean()` returns a plain object — nothing here needs a hydrated document.
    const event = await Event.findOne({ slug: normalized }).lean();

    if (!event) {
      return NextResponse.json({ message: "Event not found" }, { status: 404 });
    }

    return NextResponse.json(
      { message: "Event fetched successfully", event },
      { status: 200 },
    );
  } catch (error) {
    console.error(error);
    return NextResponse.json(
      {
        message: "Event fetching failed",
        error: error instanceof Error ? error.message : "unknown",
      },
      { status: 500 },
    );
  }
}
